name: PITest

# Run this workflow every time a new commit pushed to your repository
on: pull_request

permissions:
  # contents permission to clone the repository
  contents: read
  # issues and pull-requests permissions to write results as pull
  # request comments. Omit them if you don't need summary comments
  issues: write
  pull-requests: write
  # To report GitHub Actions status checks. Omit if you don't need
  # to update commit status
  statuses: write
  checks: write # for the upload I think

jobs:
  pitest:
    name: Mutation Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run and Comment
        run: ./gradlew --no-configuration-cache pitest-github
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
